#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IS220.N12
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HOTEL_BOOKING")]
	public partial class LinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertSERVICE_SUPPLIED(SERVICE_SUPPLIED instance);
    partial void UpdateSERVICE_SUPPLIED(SERVICE_SUPPLIED instance);
    partial void DeleteSERVICE_SUPPLIED(SERVICE_SUPPLIED instance);
    #endregion
		
		public LinqDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HOTEL_BOOKINGConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SERVICE_SUPPLIED> SERVICE_SUPPLIEDs
		{
			get
			{
				return this.GetTable<SERVICE_SUPPLIED>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FindProperty")]
		public ISingleResult<FindPropertyResult> FindProperty([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PlaceName", DbType="NVarChar(250)")] string placeName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BedNum", DbType="Int")] System.Nullable<int> bedNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CheckIn", DbType="SmallDateTime")] System.Nullable<System.DateTime> checkIn, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CheckOut", DbType="SmallDateTime")] System.Nullable<System.DateTime> checkOut)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), placeName, bedNum, checkIn, checkOut);
			return ((ISingleResult<FindPropertyResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ShowPropertyInPlace")]
		public ISingleResult<ShowPropertyInPlaceResult> ShowPropertyInPlace([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PlaceName", DbType="NVarChar(250)")] string placeName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), placeName);
			return ((ISingleResult<ShowPropertyInPlaceResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FindPropertyASC")]
		public ISingleResult<FindPropertyASCResult> FindPropertyASC([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PlaceName", DbType="NVarChar(250)")] string placeName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BedNum", DbType="Int")] System.Nullable<int> bedNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CheckIn", DbType="SmallDateTime")] System.Nullable<System.DateTime> checkIn, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CheckOut", DbType="SmallDateTime")] System.Nullable<System.DateTime> checkOut)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), placeName, bedNum, checkIn, checkOut);
			return ((ISingleResult<FindPropertyASCResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.FindPropertyDESC")]
		public ISingleResult<FindPropertyDESCResult> FindPropertyDESC([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PlaceName", DbType="NVarChar(250)")] string placeName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BedNum", DbType="Int")] System.Nullable<int> bedNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CheckIn", DbType="SmallDateTime")] System.Nullable<System.DateTime> checkIn, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CheckOut", DbType="SmallDateTime")] System.Nullable<System.DateTime> checkOut)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), placeName, bedNum, checkIn, checkOut);
			return ((ISingleResult<FindPropertyDESCResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.INFOROOM")]
		public ISingleResult<INFOROOMResult> INFOROOM([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PropertyID", DbType="Int")] System.Nullable<int> propertyID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BedNum", DbType="Int")] System.Nullable<int> bedNum, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CheckIn", DbType="SmallDateTime")] System.Nullable<System.DateTime> checkIn, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CheckOut", DbType="SmallDateTime")] System.Nullable<System.DateTime> checkOut)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), propertyID, bedNum, checkIn, checkOut);
			return ((ISingleResult<INFOROOMResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InfoService")]
		public ISingleResult<InfoServiceResult> InfoService([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PropertyID", DbType="Int")] System.Nullable<int> propertyID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), propertyID);
			return ((ISingleResult<InfoServiceResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.UPCOMMING")]
		public ISingleResult<UPCOMMINGResult> UPCOMMING([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CusID", DbType="Int")] System.Nullable<int> cusID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cusID);
			return ((ISingleResult<UPCOMMINGResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.STATISTICDAY_END")]
		public ISingleResult<STATISTICDAY_ENDResult> STATISTICDAY_END([global::System.Data.Linq.Mapping.ParameterAttribute(Name="End", DbType="SmallDateTime")] System.Nullable<System.DateTime> end, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProID", DbType="Int")] System.Nullable<int> proID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), end, proID);
			return ((ISingleResult<STATISTICDAY_ENDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.STATISTICYEAR_START")]
		public ISingleResult<STATISTICYEAR_STARTResult> STATISTICYEAR_START([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Start", DbType="SmallDateTime")] System.Nullable<System.DateTime> start, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProID", DbType="Int")] System.Nullable<int> proID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), start, proID);
			return ((ISingleResult<STATISTICYEAR_STARTResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.STATISTICDAY_FULL")]
		public ISingleResult<STATISTICDAY_FULLResult> STATISTICDAY_FULL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Start", DbType="SmallDateTime")] System.Nullable<System.DateTime> start, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="End", DbType="SmallDateTime")] System.Nullable<System.DateTime> end, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProID", DbType="Int")] System.Nullable<int> proID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), start, end, proID);
			return ((ISingleResult<STATISTICDAY_FULLResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.STATISTICDAY_START")]
		public ISingleResult<STATISTICDAY_STARTResult> STATISTICDAY_START([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Start", DbType="SmallDateTime")] System.Nullable<System.DateTime> start, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProID", DbType="Int")] System.Nullable<int> proID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), start, proID);
			return ((ISingleResult<STATISTICDAY_STARTResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.STATISTICMONTH_END")]
		public ISingleResult<STATISTICMONTH_ENDResult> STATISTICMONTH_END([global::System.Data.Linq.Mapping.ParameterAttribute(Name="End", DbType="SmallDateTime")] System.Nullable<System.DateTime> end, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProID", DbType="Int")] System.Nullable<int> proID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), end, proID);
			return ((ISingleResult<STATISTICMONTH_ENDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.STATISTICMONTH_FULL")]
		public ISingleResult<STATISTICMONTH_FULLResult> STATISTICMONTH_FULL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Start", DbType="SmallDateTime")] System.Nullable<System.DateTime> start, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="End", DbType="SmallDateTime")] System.Nullable<System.DateTime> end, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProID", DbType="Int")] System.Nullable<int> proID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), start, end, proID);
			return ((ISingleResult<STATISTICMONTH_FULLResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.STATISTICMONTH_START")]
		public ISingleResult<STATISTICMONTH_STARTResult> STATISTICMONTH_START([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Start", DbType="SmallDateTime")] System.Nullable<System.DateTime> start, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProID", DbType="Int")] System.Nullable<int> proID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), start, proID);
			return ((ISingleResult<STATISTICMONTH_STARTResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.STATISTICYEAR_END")]
		public ISingleResult<STATISTICYEAR_ENDResult> STATISTICYEAR_END([global::System.Data.Linq.Mapping.ParameterAttribute(Name="End", DbType="SmallDateTime")] System.Nullable<System.DateTime> end, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProID", DbType="Int")] System.Nullable<int> proID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), end, proID);
			return ((ISingleResult<STATISTICYEAR_ENDResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.STATISTICYEAR_FULL")]
		public ISingleResult<STATISTICYEAR_FULLResult> STATISTICYEAR_FULL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Start", DbType="SmallDateTime")] System.Nullable<System.DateTime> start, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="End", DbType="SmallDateTime")] System.Nullable<System.DateTime> end, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProID", DbType="Int")] System.Nullable<int> proID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), start, end, proID);
			return ((ISingleResult<STATISTICYEAR_FULLResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PROPERTY_RESERVATION_BASIC")]
		public ISingleResult<PROPERTY_RESERVATION_BASICResult> PROPERTY_RESERVATION_BASIC([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProID", DbType="Int")] System.Nullable<int> proID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Choice", DbType="Int")] System.Nullable<int> choice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Start", DbType="SmallDateTime")] System.Nullable<System.DateTime> start, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="End", DbType="SmallDateTime")] System.Nullable<System.DateTime> end)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), proID, choice, start, end);
			return ((ISingleResult<PROPERTY_RESERVATION_BASICResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PROPERTY_RESERVATION_TYPEROOM")]
		public ISingleResult<PROPERTY_RESERVATION_TYPEROOMResult> PROPERTY_RESERVATION_TYPEROOM([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProID", DbType="Int")] System.Nullable<int> proID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Choice", DbType="Int")] System.Nullable<int> choice, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Start", DbType="SmallDateTime")] System.Nullable<System.DateTime> start, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="End", DbType="SmallDateTime")] System.Nullable<System.DateTime> end, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TypeRoom", DbType="VarChar(255)")] string typeRoom)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), proID, choice, start, end, typeRoom);
			return ((ISingleResult<PROPERTY_RESERVATION_TYPEROOMResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LIST_RATES_FILTER")]
		public ISingleResult<LIST_RATES_FILTERResult> LIST_RATES_FILTER([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProID", DbType="Int")] System.Nullable<int> proID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TypeRoom", DbType="VarChar(255)")] string typeRoom, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StatusRoom", DbType="Int")] System.Nullable<int> statusRoom)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), proID, typeRoom, statusRoom);
			return ((ISingleResult<LIST_RATES_FILTERResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LIST_RATES")]
		public ISingleResult<LIST_RATESResult> LIST_RATES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProID", DbType="Int")] System.Nullable<int> proID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), proID);
			return ((ISingleResult<LIST_RATESResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SERVICE_SUPPLIED")]
	public partial class SERVICE_SUPPLIED : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PropertyID;
		
		private int _ServiceID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPropertyIDChanging(int value);
    partial void OnPropertyIDChanged();
    partial void OnServiceIDChanging(int value);
    partial void OnServiceIDChanged();
    #endregion
		
		public SERVICE_SUPPLIED()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PropertyID
		{
			get
			{
				return this._PropertyID;
			}
			set
			{
				if ((this._PropertyID != value))
				{
					this.OnPropertyIDChanging(value);
					this.SendPropertyChanging();
					this._PropertyID = value;
					this.SendPropertyChanged("PropertyID");
					this.OnPropertyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ServiceID
		{
			get
			{
				return this._ServiceID;
			}
			set
			{
				if ((this._ServiceID != value))
				{
					this.OnServiceIDChanging(value);
					this.SendPropertyChanging();
					this._ServiceID = value;
					this.SendPropertyChanged("ServiceID");
					this.OnServiceIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class FindPropertyResult
	{
		
		private int _PropertyID;
		
		private string _PropertyName;
		
		private string _Image_Property;
		
		private string _Address_Property;
		
		private decimal _Price;
		
		private string _TypeOfRoom;
		
		private System.Nullable<int> _Point;
		
		public FindPropertyResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyID", DbType="Int NOT NULL")]
		public int PropertyID
		{
			get
			{
				return this._PropertyID;
			}
			set
			{
				if ((this._PropertyID != value))
				{
					this._PropertyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string PropertyName
		{
			get
			{
				return this._PropertyName;
			}
			set
			{
				if ((this._PropertyName != value))
				{
					this._PropertyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image_Property", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string Image_Property
		{
			get
			{
				return this._Image_Property;
			}
			set
			{
				if ((this._Image_Property != value))
				{
					this._Image_Property = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_Property", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Address_Property
		{
			get
			{
				return this._Address_Property;
			}
			set
			{
				if ((this._Address_Property != value))
				{
					this._Address_Property = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Money NOT NULL")]
		public decimal Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeOfRoom", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TypeOfRoom
		{
			get
			{
				return this._TypeOfRoom;
			}
			set
			{
				if ((this._TypeOfRoom != value))
				{
					this._TypeOfRoom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Point", DbType="Int")]
		public System.Nullable<int> Point
		{
			get
			{
				return this._Point;
			}
			set
			{
				if ((this._Point != value))
				{
					this._Point = value;
				}
			}
		}
	}
	
	public partial class ShowPropertyInPlaceResult
	{
		
		private int _PropertyID;
		
		private string _PropertyName;
		
		private string _Image_Property;
		
		private string _Address_Property;
		
		private decimal _Price;
		
		private string _TypeOfRoom;
		
		private System.Nullable<int> _Point;
		
		public ShowPropertyInPlaceResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyID", DbType="Int NOT NULL")]
		public int PropertyID
		{
			get
			{
				return this._PropertyID;
			}
			set
			{
				if ((this._PropertyID != value))
				{
					this._PropertyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string PropertyName
		{
			get
			{
				return this._PropertyName;
			}
			set
			{
				if ((this._PropertyName != value))
				{
					this._PropertyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image_Property", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string Image_Property
		{
			get
			{
				return this._Image_Property;
			}
			set
			{
				if ((this._Image_Property != value))
				{
					this._Image_Property = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_Property", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Address_Property
		{
			get
			{
				return this._Address_Property;
			}
			set
			{
				if ((this._Address_Property != value))
				{
					this._Address_Property = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Money NOT NULL")]
		public decimal Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeOfRoom", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TypeOfRoom
		{
			get
			{
				return this._TypeOfRoom;
			}
			set
			{
				if ((this._TypeOfRoom != value))
				{
					this._TypeOfRoom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Point", DbType="Int")]
		public System.Nullable<int> Point
		{
			get
			{
				return this._Point;
			}
			set
			{
				if ((this._Point != value))
				{
					this._Point = value;
				}
			}
		}
	}
	
	public partial class FindPropertyASCResult
	{
		
		private int _PropertyID;
		
		private string _PropertyName;
		
		private string _Image_Property;
		
		private string _Address_Property;
		
		private decimal _Price;
		
		private string _TypeOfRoom;
		
		private System.Nullable<int> _Point;
		
		public FindPropertyASCResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyID", DbType="Int NOT NULL")]
		public int PropertyID
		{
			get
			{
				return this._PropertyID;
			}
			set
			{
				if ((this._PropertyID != value))
				{
					this._PropertyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string PropertyName
		{
			get
			{
				return this._PropertyName;
			}
			set
			{
				if ((this._PropertyName != value))
				{
					this._PropertyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image_Property", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string Image_Property
		{
			get
			{
				return this._Image_Property;
			}
			set
			{
				if ((this._Image_Property != value))
				{
					this._Image_Property = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_Property", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Address_Property
		{
			get
			{
				return this._Address_Property;
			}
			set
			{
				if ((this._Address_Property != value))
				{
					this._Address_Property = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Money NOT NULL")]
		public decimal Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeOfRoom", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TypeOfRoom
		{
			get
			{
				return this._TypeOfRoom;
			}
			set
			{
				if ((this._TypeOfRoom != value))
				{
					this._TypeOfRoom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Point", DbType="Int")]
		public System.Nullable<int> Point
		{
			get
			{
				return this._Point;
			}
			set
			{
				if ((this._Point != value))
				{
					this._Point = value;
				}
			}
		}
	}
	
	public partial class FindPropertyDESCResult
	{
		
		private int _PropertyID;
		
		private string _PropertyName;
		
		private string _Image_Property;
		
		private string _Address_Property;
		
		private decimal _Price;
		
		private string _TypeOfRoom;
		
		private System.Nullable<int> _Point;
		
		public FindPropertyDESCResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyID", DbType="Int NOT NULL")]
		public int PropertyID
		{
			get
			{
				return this._PropertyID;
			}
			set
			{
				if ((this._PropertyID != value))
				{
					this._PropertyID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string PropertyName
		{
			get
			{
				return this._PropertyName;
			}
			set
			{
				if ((this._PropertyName != value))
				{
					this._PropertyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image_Property", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string Image_Property
		{
			get
			{
				return this._Image_Property;
			}
			set
			{
				if ((this._Image_Property != value))
				{
					this._Image_Property = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_Property", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Address_Property
		{
			get
			{
				return this._Address_Property;
			}
			set
			{
				if ((this._Address_Property != value))
				{
					this._Address_Property = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Money NOT NULL")]
		public decimal Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeOfRoom", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TypeOfRoom
		{
			get
			{
				return this._TypeOfRoom;
			}
			set
			{
				if ((this._TypeOfRoom != value))
				{
					this._TypeOfRoom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Point", DbType="Int")]
		public System.Nullable<int> Point
		{
			get
			{
				return this._Point;
			}
			set
			{
				if ((this._Point != value))
				{
					this._Point = value;
				}
			}
		}
	}
	
	public partial class INFOROOMResult
	{
		
		private int _RoomID;
		
		private string _RoomName;
		
		private string _TypeOfRoom;
		
		private int _BedNum;
		
		private decimal _Price;
		
		private string _Image_Room;
		
		private int _PropertyID;
		
		public INFOROOMResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomID", DbType="Int NOT NULL")]
		public int RoomID
		{
			get
			{
				return this._RoomID;
			}
			set
			{
				if ((this._RoomID != value))
				{
					this._RoomID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomName", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string RoomName
		{
			get
			{
				return this._RoomName;
			}
			set
			{
				if ((this._RoomName != value))
				{
					this._RoomName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeOfRoom", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TypeOfRoom
		{
			get
			{
				return this._TypeOfRoom;
			}
			set
			{
				if ((this._TypeOfRoom != value))
				{
					this._TypeOfRoom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BedNum", DbType="Int NOT NULL")]
		public int BedNum
		{
			get
			{
				return this._BedNum;
			}
			set
			{
				if ((this._BedNum != value))
				{
					this._BedNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Money NOT NULL")]
		public decimal Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image_Room", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string Image_Room
		{
			get
			{
				return this._Image_Room;
			}
			set
			{
				if ((this._Image_Room != value))
				{
					this._Image_Room = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyID", DbType="Int NOT NULL")]
		public int PropertyID
		{
			get
			{
				return this._PropertyID;
			}
			set
			{
				if ((this._PropertyID != value))
				{
					this._PropertyID = value;
				}
			}
		}
	}
	
	public partial class InfoServiceResult
	{
		
		private string _ServiceName;
		
		public InfoServiceResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ServiceName
		{
			get
			{
				return this._ServiceName;
			}
			set
			{
				if ((this._ServiceName != value))
				{
					this._ServiceName = value;
				}
			}
		}
	}
	
	public partial class UPCOMMINGResult
	{
		
		private string _Image_Room;
		
		private string _PropertyName;
		
		private string _RoomName;
		
		private string _CheckInTime;
		
		private System.Nullable<System.DateTime> _CheckIn;
		
		private System.Nullable<decimal> _Total;
		
		private string _TypeOfRoom;
		
		public UPCOMMINGResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image_Room", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string Image_Room
		{
			get
			{
				return this._Image_Room;
			}
			set
			{
				if ((this._Image_Room != value))
				{
					this._Image_Room = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PropertyName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string PropertyName
		{
			get
			{
				return this._PropertyName;
			}
			set
			{
				if ((this._PropertyName != value))
				{
					this._PropertyName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoomName", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string RoomName
		{
			get
			{
				return this._RoomName;
			}
			set
			{
				if ((this._RoomName != value))
				{
					this._RoomName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckInTime", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string CheckInTime
		{
			get
			{
				return this._CheckInTime;
			}
			set
			{
				if ((this._CheckInTime != value))
				{
					this._CheckInTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckIn", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> CheckIn
		{
			get
			{
				return this._CheckIn;
			}
			set
			{
				if ((this._CheckIn != value))
				{
					this._CheckIn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Money")]
		public System.Nullable<decimal> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeOfRoom", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TypeOfRoom
		{
			get
			{
				return this._TypeOfRoom;
			}
			set
			{
				if ((this._TypeOfRoom != value))
				{
					this._TypeOfRoom = value;
				}
			}
		}
	}
	
	public partial class STATISTICDAY_ENDResult
	{
		
		private System.Nullable<int> _Day;
		
		private System.Nullable<int> _total;
		
		public STATISTICDAY_ENDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Day", DbType="Int")]
		public System.Nullable<int> Day
		{
			get
			{
				return this._Day;
			}
			set
			{
				if ((this._Day != value))
				{
					this._Day = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Int")]
		public System.Nullable<int> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this._total = value;
				}
			}
		}
	}
	
	public partial class STATISTICYEAR_STARTResult
	{
		
		private System.Nullable<int> _Year;
		
		private System.Nullable<int> _total;
		
		public STATISTICYEAR_STARTResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="Int")]
		public System.Nullable<int> Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this._Year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Int")]
		public System.Nullable<int> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this._total = value;
				}
			}
		}
	}
	
	public partial class STATISTICDAY_FULLResult
	{
		
		private System.Nullable<int> _Day;
		
		private System.Nullable<int> _total;
		
		public STATISTICDAY_FULLResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Day", DbType="Int")]
		public System.Nullable<int> Day
		{
			get
			{
				return this._Day;
			}
			set
			{
				if ((this._Day != value))
				{
					this._Day = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Int")]
		public System.Nullable<int> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this._total = value;
				}
			}
		}
	}
	
	public partial class STATISTICDAY_STARTResult
	{
		
		private System.Nullable<int> _Day;
		
		private System.Nullable<int> _total;
		
		public STATISTICDAY_STARTResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Day", DbType="Int")]
		public System.Nullable<int> Day
		{
			get
			{
				return this._Day;
			}
			set
			{
				if ((this._Day != value))
				{
					this._Day = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Int")]
		public System.Nullable<int> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this._total = value;
				}
			}
		}
	}
	
	public partial class STATISTICMONTH_ENDResult
	{
		
		private System.Nullable<int> _Month;
		
		private System.Nullable<int> _total;
		
		public STATISTICMONTH_ENDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="Int")]
		public System.Nullable<int> Month
		{
			get
			{
				return this._Month;
			}
			set
			{
				if ((this._Month != value))
				{
					this._Month = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Int")]
		public System.Nullable<int> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this._total = value;
				}
			}
		}
	}
	
	public partial class STATISTICMONTH_FULLResult
	{
		
		private System.Nullable<int> _Month;
		
		private System.Nullable<int> _total;
		
		public STATISTICMONTH_FULLResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="Int")]
		public System.Nullable<int> Month
		{
			get
			{
				return this._Month;
			}
			set
			{
				if ((this._Month != value))
				{
					this._Month = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Int")]
		public System.Nullable<int> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this._total = value;
				}
			}
		}
	}
	
	public partial class STATISTICMONTH_STARTResult
	{
		
		private System.Nullable<int> _Month;
		
		private System.Nullable<int> _total;
		
		public STATISTICMONTH_STARTResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="Int")]
		public System.Nullable<int> Month
		{
			get
			{
				return this._Month;
			}
			set
			{
				if ((this._Month != value))
				{
					this._Month = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Int")]
		public System.Nullable<int> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this._total = value;
				}
			}
		}
	}
	
	public partial class STATISTICYEAR_ENDResult
	{
		
		private System.Nullable<int> _Year;
		
		private System.Nullable<int> _total;
		
		public STATISTICYEAR_ENDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="Int")]
		public System.Nullable<int> Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this._Year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Int")]
		public System.Nullable<int> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this._total = value;
				}
			}
		}
	}
	
	public partial class STATISTICYEAR_FULLResult
	{
		
		private System.Nullable<int> _year;
		
		private System.Nullable<int> _total;
		
		public STATISTICYEAR_FULLResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_year", DbType="Int")]
		public System.Nullable<int> year
		{
			get
			{
				return this._year;
			}
			set
			{
				if ((this._year != value))
				{
					this._year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Int")]
		public System.Nullable<int> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this._total = value;
				}
			}
		}
	}
	
	public partial class PROPERTY_RESERVATION_BASICResult
	{
		
		private int _ReservationID;
		
		private int _BedNum;
		
		private System.Nullable<System.DateTime> _CheckIn;
		
		private System.Nullable<System.DateTime> _CheckOut;
		
		private string _TypeOfRoom;
		
		private int _Status_Reservation;
		
		private System.Nullable<decimal> _Total;
		
		public PROPERTY_RESERVATION_BASICResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReservationID", DbType="Int NOT NULL")]
		public int ReservationID
		{
			get
			{
				return this._ReservationID;
			}
			set
			{
				if ((this._ReservationID != value))
				{
					this._ReservationID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BedNum", DbType="Int NOT NULL")]
		public int BedNum
		{
			get
			{
				return this._BedNum;
			}
			set
			{
				if ((this._BedNum != value))
				{
					this._BedNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckIn", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> CheckIn
		{
			get
			{
				return this._CheckIn;
			}
			set
			{
				if ((this._CheckIn != value))
				{
					this._CheckIn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckOut", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> CheckOut
		{
			get
			{
				return this._CheckOut;
			}
			set
			{
				if ((this._CheckOut != value))
				{
					this._CheckOut = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeOfRoom", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TypeOfRoom
		{
			get
			{
				return this._TypeOfRoom;
			}
			set
			{
				if ((this._TypeOfRoom != value))
				{
					this._TypeOfRoom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status_Reservation", DbType="Int NOT NULL")]
		public int Status_Reservation
		{
			get
			{
				return this._Status_Reservation;
			}
			set
			{
				if ((this._Status_Reservation != value))
				{
					this._Status_Reservation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Money")]
		public System.Nullable<decimal> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
	}
	
	public partial class PROPERTY_RESERVATION_TYPEROOMResult
	{
		
		private int _ReservationID;
		
		private int _BedNum;
		
		private System.Nullable<System.DateTime> _CheckIn;
		
		private System.Nullable<System.DateTime> _CheckOut;
		
		private string _TypeOfRoom;
		
		private int _Status_Reservation;
		
		private System.Nullable<decimal> _Total;
		
		public PROPERTY_RESERVATION_TYPEROOMResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReservationID", DbType="Int NOT NULL")]
		public int ReservationID
		{
			get
			{
				return this._ReservationID;
			}
			set
			{
				if ((this._ReservationID != value))
				{
					this._ReservationID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BedNum", DbType="Int NOT NULL")]
		public int BedNum
		{
			get
			{
				return this._BedNum;
			}
			set
			{
				if ((this._BedNum != value))
				{
					this._BedNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckIn", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> CheckIn
		{
			get
			{
				return this._CheckIn;
			}
			set
			{
				if ((this._CheckIn != value))
				{
					this._CheckIn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckOut", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> CheckOut
		{
			get
			{
				return this._CheckOut;
			}
			set
			{
				if ((this._CheckOut != value))
				{
					this._CheckOut = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeOfRoom", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TypeOfRoom
		{
			get
			{
				return this._TypeOfRoom;
			}
			set
			{
				if ((this._TypeOfRoom != value))
				{
					this._TypeOfRoom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status_Reservation", DbType="Int NOT NULL")]
		public int Status_Reservation
		{
			get
			{
				return this._Status_Reservation;
			}
			set
			{
				if ((this._Status_Reservation != value))
				{
					this._Status_Reservation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Money")]
		public System.Nullable<decimal> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
	}
	
	public partial class LIST_RATES_FILTERResult
	{
		
		private System.Nullable<int> _Quantity;
		
		private string _TypeOfRoom;
		
		private System.Nullable<decimal> _Price;
		
		private int _Status_Reservation;
		
		public LIST_RATES_FILTERResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int")]
		public System.Nullable<int> Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeOfRoom", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TypeOfRoom
		{
			get
			{
				return this._TypeOfRoom;
			}
			set
			{
				if ((this._TypeOfRoom != value))
				{
					this._TypeOfRoom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Money")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status_Reservation", DbType="Int NOT NULL")]
		public int Status_Reservation
		{
			get
			{
				return this._Status_Reservation;
			}
			set
			{
				if ((this._Status_Reservation != value))
				{
					this._Status_Reservation = value;
				}
			}
		}
	}
	
	public partial class LIST_RATESResult
	{
		
		private System.Nullable<int> _Quantity;
		
		private string _TypeOfRoom;
		
		private System.Nullable<decimal> _Price;
		
		private int _Status_Reservation;
		
		public LIST_RATESResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Int")]
		public System.Nullable<int> Quantity
		{
			get
			{
				return this._Quantity;
			}
			set
			{
				if ((this._Quantity != value))
				{
					this._Quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeOfRoom", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TypeOfRoom
		{
			get
			{
				return this._TypeOfRoom;
			}
			set
			{
				if ((this._TypeOfRoom != value))
				{
					this._TypeOfRoom = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price", DbType="Money")]
		public System.Nullable<decimal> Price
		{
			get
			{
				return this._Price;
			}
			set
			{
				if ((this._Price != value))
				{
					this._Price = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status_Reservation", DbType="Int NOT NULL")]
		public int Status_Reservation
		{
			get
			{
				return this._Status_Reservation;
			}
			set
			{
				if ((this._Status_Reservation != value))
				{
					this._Status_Reservation = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
